{
  "openapi": "3.0.0",
  "info": {
    "title": "tara",
    "description": "",
    "version": "1.0.0"
  },
  "servers": [],
  "paths": {
    "/tara/login": {
      "post": {
        "tags": [
          "用户登录接口"
        ],
        "summary": "用户登录接口",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "lt15191796518@163.com",
                  "password": "Sigvoid123"
                }
              }
            }
          }
        }
      }
    },
    "/tara/logout": {
      "post": {
        "tags": [
          "用户登出接口"
        ],
        "summary": "用户登出接口",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/register": {
      "post": {
        "tags": [
          "用户注册接口"
        ],
        "summary": "用户注册接口",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "confirmPassword": "litao19980325.",
                  "email": "lt15191796518@163.com",
                  "inviteCode": "string",
                  "password": "litao19980325.",
                  "verifyCode": "string"
                }
              }
            }
          }
        }
      }
    },
    "/tara/resetPassword": {
      "post": {
        "tags": [
          "重置密码接口"
        ],
        "summary": "重置密码接口",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/sendVerifyCode": {
      "post": {
        "tags": [
          "发送验证码接口 -- old"
        ],
        "summary": "发送验证码接口 -- old",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/checkAccount": {
      "post": {
        "tags": [
          "检查账号接口"
        ],
        "summary": "检查账号接口",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "lt15191796518@163.com"
                }
              }
            }
          }
        }
      }
    },
    "/tara/sendVerifyCodeForRegister": {
      "post": {
        "tags": [
          "发送注册验证码接口"
        ],
        "summary": "发送注册验证码接口",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "lt15191796518@163.com"
                }
              }
            }
          }
        }
      }
    },
    "/tara/sendVerifyCodeForPasswordReset": {
      "post": {
        "tags": [
          "发送密码重置验证码接口"
        ],
        "summary": "发送密码重置验证码接口",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "lt15191796518@163.com"
                }
              }
            }
          }
        }
      }
    },
    "/tara/file/images/:path": {
      "get": {
        "tags": [
          "处理图片下载请求"
        ],
        "summary": "处理图片下载请求",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/file/report/:project_id/:report_type": {
      "get": {
        "tags": [
          "Download TARA Report"
        ],
        "summary": "Download TARA Report",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/report/export/asset/:project_id": {
      "get": {
        "tags": [
          "导出资产列表数据"
        ],
        "summary": "导出资产列表数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/report/export/damage/:project_id": {
      "get": {
        "tags": [
          "导出损害场景数据"
        ],
        "summary": "导出损害场景数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/report/export/full/:project_id": {
      "get": {
        "tags": [
          "导出完整的TARA项目报告"
        ],
        "summary": "导出完整的TARA项目报告",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/report/export/network-security-goal/:project_id": {
      "get": {
        "tags": [
          "导出网络安全目标数据"
        ],
        "summary": "导出网络安全目标数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/report/export/threat/:project_id": {
      "get": {
        "tags": [
          "导出威胁场景数据"
        ],
        "summary": "导出威胁场景数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/map/addchannel": {
      "post": {
        "tags": [
          "添加通道"
        ],
        "summary": "添加通道",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "componentName": "",
                  "fromApi": {
                    "ApiIDStr": "1",
                    "apiName": "接口1",
                    "protocol": "",
                    "x": 0,
                    "y": 0
                  },
                  "fromElementComponentID": "string",
                  "pointList": [
                    {
                      "fromAPI": "string",
                      "fromElementComponentID": "string",
                      "toAPI": "string",
                      "toElementComponentID": "string",
                      "vertices": "string"
                    }
                  ],
                  "position": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                  },
                  "projectID": "string",
                  "toApi": {
                    "ApiIDStr": "string",
                    "apiName": "string",
                    "protocol": "string",
                    "x": 0,
                    "y": 0
                  },
                  "toElementComponentID": "string"
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/adddata": {
      "post": {
        "tags": [
          "添加数据 - done"
        ],
        "summary": "添加数据 - done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "component": "",
                  "componentName": "未命名数据",
                  "projectID": "749297120889389056",
                  "position": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                  },
                  "elementComponentID": "COMP-3"
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/addelement": {
      "post": {
        "tags": [
          "添加组件 - done"
        ],
        "summary": "添加组件 - done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/map/addenvironment": {
      "post": {
        "tags": [
          "添加环境- done"
        ],
        "summary": "添加环境- done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "componentDesc": "环境3435435描述",
                  "componentName": "test123",
                  "position": {
                    "x": 0,
                    "y": 0
                  },
                  "projectID": "749297120889389056",
                  "size": {
                    "height": 0,
                    "length": 0,
                    "width": 0
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/addfunction": {
      "post": {
        "tags": [
          "添加功能"
        ],
        "summary": "添加功能",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "componentIds": [
                    "string"
                  ],
                  "funcDesc": "string",
                  "funcName": "string",
                  "projectID": "string"
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/copyelement": {
      "post": {
        "tags": [
          "复制组件- done"
        ],
        "summary": "复制组件- done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "elementComponentID": "COMP-8",
                  "projectID": "{{projectID}}"
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/detail": {
      "post": {
        "tags": [
          "获取拓扑图详情-done"
        ],
        "summary": "获取拓扑图详情-done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "projectID": "string"
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/editattribute": {
      "post": {
        "tags": [
          "编辑元器件属性"
        ],
        "summary": "编辑元器件属性",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "apiList": [
                    {
                      "ApiIDStr": "string",
                      "apiName": "string",
                      "protocol": "string",
                      "x": 0,
                      "y": 0
                    }
                  ],
                  "componentDesc": "string",
                  "componentID": "string",
                  "componentName": "string",
                  "componentType": 0,
                  "dataFlowList": [
                    {
                      "channelComponentID": "string",
                      "dataFlowComponentID": "string",
                      "direction": 0,
                      "fromAPI": {
                        "ApiIDStr": "string",
                        "apiName": "string",
                        "protocol": "string",
                        "x": 0,
                        "y": 0
                      },
                      "fromElementComponentID": "string",
                      "fromElementComponentName": "string",
                      "toAPI": {
                        "ApiIDStr": "string",
                        "apiName": "string",
                        "protocol": "string",
                        "x": 0,
                        "y": 0
                      },
                      "toElementComponentID": "string",
                      "toElementComponentName": "string",
                      "vertices": [
                        {
                          "x": 0,
                          "y": 0
                        }
                      ]
                    }
                  ],
                  "dataList": [
                    {
                      "component": "string",
                      "componentName": "string",
                      "componentType": 0,
                      "dataComponentID": "string",
                      "elementComponentID": "string",
                      "position": {
                        "x": 0,
                        "y": 0,
                        "z": 0
                      }
                    }
                  ],
                  "hardwareList": [
                    {
                      "hardwareID": 0,
                      "hardwareName": "string"
                    }
                  ],
                  "projectID": "string",
                  "softwareList": [
                    {
                      "softwareID": 0,
                      "softwareName": "string"
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/editchannel": {
      "post": {
        "tags": [
          "编辑通道"
        ],
        "summary": "编辑通道",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "channelComponentID": "string",
                  "componentDesc": "string",
                  "componentName": "string",
                  "curFromElementComponentID": "string",
                  "curToElementComponentID": "string",
                  "direction": 0,
                  "fromApi": {
                    "ApiIDStr": "string",
                    "apiName": "string",
                    "protocol": "string",
                    "x": 0,
                    "y": 0
                  },
                  "newFromElementComponentID": "string",
                  "newToElementComponentID": "string",
                  "opType": 0,
                  "pointList": [
                    {
                      "fromAPI": "string",
                      "fromElementComponentID": "string",
                      "toAPI": "string",
                      "toElementComponentID": "string",
                      "vertices": "string"
                    }
                  ],
                  "position": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                  },
                  "projectID": "string",
                  "toApi": {
                    "ApiIDStr": "string",
                    "apiName": "string",
                    "protocol": "string",
                    "x": 0,
                    "y": 0
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/editdata": {
      "post": {
        "tags": [
          "编辑数据- done"
        ],
        "summary": "编辑数据- done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "dataComponentID": "string",
                  "newElementComponentID": "string",
                  "opType": 0,
                  "position": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                  },
                  "projectID": "string"
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/editelement": {
      "post": {
        "tags": [
          "编辑组件- done"
        ],
        "summary": "编辑组件- done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "belongEnvironmentComponentID": "string",
                  "elementComponentID": "string",
                  "ext": "string",
                  "opType": 0,
                  "position": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                  },
                  "projectID": "string",
                  "size": {
                    "height": 0,
                    "length": 0,
                    "width": 0
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/editenvironment": {
      "post": {
        "tags": [
          "编辑环境- done"
        ],
        "summary": "编辑环境- done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "componentDesc": "string",
                  "componentName": "string",
                  "environmentID": "string",
                  "opType": 0,
                  "position": {
                    "x": 0,
                    "y": 0,
                    "z": 0
                  },
                  "projectID": "string",
                  "size": {
                    "height": 0,
                    "length": 0,
                    "width": 0
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/editfunction": {
      "post": {
        "tags": [
          "编辑功能"
        ],
        "summary": "编辑功能",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "componentIds": [
                    "string"
                  ],
                  "funcDesc": "string",
                  "funcID": "string",
                  "funcName": "string",
                  "opType": 0,
                  "projectID": "string"
                }
              }
            }
          }
        }
      }
    },
    "/tara/map/getcomponentlibraryinfo": {
      "get": {
        "tags": [
          "获取元器件库信息- done"
        ],
        "summary": "获取元器件库信息- done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/project/create": {
      "post": {
        "tags": [
          "创建项目"
        ],
        "summary": "创建项目",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "{{randomName}}"
                }
              }
            }
          }
        }
      }
    },
    "/tara/project/delete": {
      "post": {
        "tags": [
          "删除项目"
        ],
        "summary": "删除项目",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "projectID": "{{projectID}}"
                }
              }
            }
          }
        }
      }
    },
    "/tara/project/detail": {
      "post": {
        "tags": [
          "获取项目详情"
        ],
        "summary": "获取项目详情",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "projectID": "{{projectID}}",
                  "projectStage": 0
                }
              }
            }
          }
        }
      }
    },
    "/tara/project/info": {
      "post": {
        "tags": [
          "获取项目基本信息"
        ],
        "summary": "获取项目基本信息",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "projectID": "{{projectID}}"
                }
              }
            }
          }
        }
      }
    },
    "/tara/project/list": {
      "get": {
        "tags": [
          "获取项目列表"
        ],
        "summary": "获取项目列表",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/project/statistics": {
      "post": {
        "tags": [
          "获取项目统计信息"
        ],
        "summary": "获取项目统计信息",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "projectID": "{{projectID}}"
                }
              }
            }
          }
        }
      }
    },
    "/tara/project/update": {
      "post": {
        "tags": [
          "更新项目"
        ],
        "summary": "更新项目",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "assumptionsAndConstraints": "string",
                  "description": "string",
                  "environmentAndBoundary": "string",
                  "fileIds": [
                    "string"
                  ],
                  "name": "string",
                  "projectID": "{{projectID}}"
                }
              }
            }
          }
        }
      }
    },
    "/tara/project/upload/cover": {
      "post": {
        "tags": [
          "上传项目封面"
        ],
        "summary": "上传项目封面",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "coverImageBase64": "string",
                  "projectID": "{{projectID}}"
                }
              }
            }
          }
        }
      }
    },
    "/tara/survey/submit": {
      "post": {
        "tags": [
          "用户信息"
        ],
        "summary": "用户信息",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "company": "string",
                  "country": "string",
                  "email": "string",
                  "name": "string",
                  "phoneNumber": "string",
                  "requirement": "string",
                  "role": "string"
                }
              }
            }
          }
        }
      }
    },
    "/tara/user/info": {
      "get": {
        "tags": [
          "获取用户信息- done"
        ],
        "summary": "获取用户信息- done",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/attackpath/batch/create": {
      "post": {
        "tags": [
          "批量创建攻击路径"
        ],
        "summary": "批量创建攻击路径",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/attackpath/create": {
      "post": {
        "tags": [
          "创建攻击路径"
        ],
        "summary": "创建攻击路径",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/attackpath/delete": {
      "post": {
        "tags": [
          "删除攻击路径"
        ],
        "summary": "删除攻击路径",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/attackpath/detail": {
      "post": {
        "tags": [
          "获取攻击路径详情"
        ],
        "summary": "获取攻击路径详情",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/attackpath/list": {
      "post": {
        "tags": [
          "获取攻击路径列表"
        ],
        "summary": "获取攻击路径列表",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/attackpath/update": {
      "post": {
        "tags": [
          "更新攻击路径"
        ],
        "summary": "更新攻击路径",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/damage/add": {
      "post": {
        "tags": [
          "新增损害数据"
        ],
        "summary": "新增损害数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/damage/batch/preview": {
      "post": {
        "tags": [
          "批量生成损害数据预览"
        ],
        "summary": "批量生成损害数据预览",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/damage/batch/update": {
      "post": {
        "tags": [
          "批量更新损害数据"
        ],
        "summary": "批量更新损害数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/damage/delete": {
      "post": {
        "tags": [
          "删除损害数据"
        ],
        "summary": "删除损害数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/damage/edit": {
      "post": {
        "tags": [
          "编辑损害数据"
        ],
        "summary": "编辑损害数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/damage/generate": {
      "post": {
        "tags": [
          "生成单条空白损害数据"
        ],
        "summary": "生成单条空白损害数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/damage/get": {
      "post": {
        "tags": [
          "获取损害数据"
        ],
        "summary": "获取损害数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/damage/getassetdata": {
      "post": {
        "tags": [
          "获取资产损害数据"
        ],
        "summary": "获取资产损害数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/batch/create": {
      "post": {
        "tags": [
          "批量创建数据流"
        ],
        "summary": "批量创建数据流",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/batch/delete": {
      "post": {
        "tags": [
          "批量删除数据流"
        ],
        "summary": "批量删除数据流",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/create": {
      "post": {
        "tags": [
          "创建数据流"
        ],
        "summary": "创建数据流",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/delete": {
      "post": {
        "tags": [
          "删除数据流"
        ],
        "summary": "删除数据流",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/element/delete": {
      "post": {
        "tags": [
          "删除组件关联数据流"
        ],
        "summary": "删除组件关联数据流",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/element/list": {
      "post": {
        "tags": [
          "根据组件获取数据流列表"
        ],
        "summary": "根据组件获取数据流列表",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/get": {
      "post": {
        "tags": [
          "获取数据流详情"
        ],
        "summary": "获取数据流详情",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/project/list": {
      "post": {
        "tags": [
          "获取项目数据流列表"
        ],
        "summary": "获取项目数据流列表",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/update": {
      "post": {
        "tags": [
          "更新数据流"
        ],
        "summary": "更新数据流",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/identity/analysis": {
      "post": {
        "tags": [
          "资产分析"
        ],
        "summary": "资产分析",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "projectID": "749272812606029824"
                }
              }
            }
          }
        }
      }
    },
    "/tara/asset/identity/choiceList": {
      "get": {
        "tags": [
          "获取资产选项信息列表"
        ],
        "summary": "获取资产选项信息列表",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/identity/delete": {
      "post": {
        "tags": [
          "资产删除"
        ],
        "summary": "资产删除",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/identity/edit": {
      "post": {
        "tags": [
          "资产编辑"
        ],
        "summary": "资产编辑",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/identity/identify": {
      "post": {
        "tags": [
          "资产识别"
        ],
        "summary": "资产识别",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "projectID": "string"
                }
              }
            }
          }
        }
      }
    },
    "/tara/asset/identity/getdata": {
      "post": {
        "tags": [
          "获取资产识别数据"
        ],
        "summary": "获取资产识别数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/network/add": {
      "post": {
        "tags": [
          "新增网络安全属性"
        ],
        "summary": "新增网络安全属性",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/network/batch/preview": {
      "post": {
        "tags": [
          "批量生成网络安全预览"
        ],
        "summary": "批量生成网络安全预览",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/network/batch/update": {
      "post": {
        "tags": [
          "批量更新网络安全属性"
        ],
        "summary": "批量更新网络安全属性",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/network/edit": {
      "post": {
        "tags": [
          "编辑网络安全属性"
        ],
        "summary": "编辑网络安全属性",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/risk/calculate/feasibility": {
      "post": {
        "tags": [
          "计算攻击可行性评级"
        ],
        "summary": "计算攻击可行性评级",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/risk/calculate/impact": {
      "post": {
        "tags": [
          "计算影响等级"
        ],
        "summary": "计算影响等级",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/risk/calculate/value": {
      "post": {
        "tags": [
          "计算风险值"
        ],
        "summary": "计算风险值",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/risk/get": {
      "post": {
        "tags": [
          "获取风险数据"
        ],
        "summary": "获取风险数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/risk/update/decision": {
      "post": {
        "tags": [
          "更新风险处置决策"
        ],
        "summary": "更新风险处置决策",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/risk/update/network-security-target": {
      "post": {
        "tags": [
          "更新网络安全目标字段"
        ],
        "summary": "更新网络安全目标字段",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/risk/update/threat": {
      "post": {
        "tags": [
          "更新威胁字段"
        ],
        "summary": "更新威胁字段",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/addrecord/asset": {
      "post": {
        "tags": [
          "新增资产威胁记录"
        ],
        "summary": "新增资产威胁记录",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/addrecord/damage": {
      "post": {
        "tags": [
          "新增损害威胁记录"
        ],
        "summary": "新增损害威胁记录",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/batch/preview/asset": {
      "post": {
        "tags": [
          "批量生成资产威胁数据预览"
        ],
        "summary": "批量生成资产威胁数据预览",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/batch/preview/damage": {
      "post": {
        "tags": [
          "批量生成损害威胁数据预览"
        ],
        "summary": "批量生成损害威胁数据预览",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/batch/update/asset": {
      "post": {
        "tags": [
          "批量更新资产威胁数据"
        ],
        "summary": "批量更新资产威胁数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/batch/update/damage": {
      "post": {
        "tags": [
          "批量更新损害威胁数据"
        ],
        "summary": "批量更新损害威胁数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/edit": {
      "post": {
        "tags": [
          "编辑威胁数据"
        ],
        "summary": "编辑威胁数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/get": {
      "post": {
        "tags": [
          "获取威胁数据"
        ],
        "summary": "获取威胁数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/getbyasset": {
      "post": {
        "tags": [
          "根据资产获取威胁数据"
        ],
        "summary": "根据资产获取威胁数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/getbydamage": {
      "post": {
        "tags": [
          "根据损害ID获取威胁数据"
        ],
        "summary": "根据损害ID获取威胁数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/threat/update": {
      "post": {
        "tags": [
          "更新威胁记录"
        ],
        "summary": "更新威胁记录",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/data/bind": {
      "post": {
        "tags": [
          "绑定数据到数据流"
        ],
        "summary": "绑定数据到数据流",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/data/create": {
      "post": {
        "tags": [
          "新建数据并绑定到数据流"
        ],
        "summary": "新建数据并绑定到数据流",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/data/delete": {
      "post": {
        "tags": [
          "删除数据流数据"
        ],
        "summary": "删除数据流数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/data/list": {
      "post": {
        "tags": [
          "获取数据流数据列表"
        ],
        "summary": "获取数据流数据列表",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/data/unbind": {
      "post": {
        "tags": [
          "解绑数据从数据流"
        ],
        "summary": "解绑数据从数据流",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/asset/dataflow/data/update": {
      "post": {
        "tags": [
          "更新数据流数据"
        ],
        "summary": "更新数据流数据",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/file/delete": {
      "post": {
        "tags": [
          "删除文件"
        ],
        "summary": "删除文件",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "fileIds": [
                    "{{fileIdList}}"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/tara/file/list": {
      "get": {
        "tags": [
          "读取临时文件列表"
        ],
        "summary": "读取临时文件列表",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    },
    "/tara/file/upload": {
      "post": {
        "tags": [
          "上传文件"
        ],
        "summary": "上传文件",
        "description": "",
        "parameters": [],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  }
}